### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by asdfxD** [KitsuneLab-Development/K4-DamageInfo#12]
Server crashes with this plugin when start shooting at enemys (test against bots)

CSSharp: 154
Plugins: Only CS2_DamageInfo

**Comment by K4ryuu** [comment]
The problem has been fixed within the last update.
Please update the plugin and the translation file also.

**Comment by asdfxD** [comment]
still crashes for me when first shot on enemy.

[crash.webm](https://github.com/K4ryuu/CS2_DamageInfo/assets/24253340/0204aff6-4ab0-4506-9de7-d00102e9120b)


![one plugin](https://github.com/K4ryuu/CS2_DamageInfo/assets/24253340/c5ba10e1-a782-4d31-8f81-6119590c4837)

**Comment by asdfxD** [comment]
i set this to false in config, no crash anymore.

  "center-damage-info": false,
  "console-damage-info": false,

there is still no fix for the damage calculation right now? upper (cs2) damage is different and not the same as from the plugin.
